// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Post struct {
	PostedBy      string    `json:"postedBy"`
	ServicePostID string    `json:"servicePostId"`
	Tags          []*string `json:"tags"`
	Service       string    `json:"service"`
	DatePosted    string    `json:"datePosted"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
